logging:
  level:
    org:
      springframework: info
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


currency-service:
  url: http://default.in28minutes.com
  username: defaultarunusername
  key: defaultarunkey
  hint: alwaysfromapplicationpropertiesirrespective of env.

#look at -dev property file. Also look at the code .
some:
  other:
    configurationvalue: defaultValue

yaml:
  name: application.yml
  aliases:
    - properties.yml
    - env.yml
  cors-allowed-list:
    -  http://localhost:6555
    -  ${PORTAL_URL:http://localhost:8080}
    -  ${API_URL:http://localhost:9090}
  public-api-list:
    - /api/public/**
    - hello-world-internationalized

corsallowedlistarun: shinde,arun