logging:
  level:
    org:
      springframework: info
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.security.user.name=username
#spring.security.user.password=password

currency-service:
  url: http://dev.in28minutes.com
  username: devarunusername
  key: devarunkey

##this is coming from enviroment variable set by using edit configuration of intellij
some:
  other:
    configurationvalue: ${DEV_VALUE:arunshindedevvalue}

